### ISSUE TITLE
Figure out some way for searching

### ISSUE THREAD

**Issue by mmcclimon** [societymusictheory/societymusictheory.github.io#3]
We could use just a Google site search (which wasn't working when the site was first uploaded, but seems to have been indexed now).

What would probably be better is to use some library, which would probably involve including all of the titles/abstracts somewhere as JS objects.

**Comment by bcmoseley** [comment]
This seems like a good option: https://github.com/christian-fei/Simple-Jekyll-Search

Some of the things I've found are plugins. Most plugins won't work on Github-hosted sites because Github runs Jekyll in safe mode. We could use something like https://github.com/slashdotdash/jekyll-lunr-js-search, but we'd have to either (1) host the blog on the server or (2) generate the site locally and push it to Github.

**Comment by mmcclimon** [comment]
Hey we did this!
